spring:
  application:
    name: app-frame
  
  redis:
    host: 192.168.74.130
    port: 6379
    timeout: 60000
    jedis:
      pool:
        max-active: 1000
        min-idle: 2
        max-idle: 8
        max-wait: -1